walking14

diff --git a/oadp-config/templates/patch_volumesnapshotclasses-deletionpolicy.yaml b/oadp-config/templates/patch_volumesnapshotclasses-deletionpolicy.yaml
--- a/oadp-config/templates/patch_volumesnapshotclasses-deletionpolicy.yaml
+++ b/oadp-config/templates/patch_volumesnapshotclasses-deletionpolicy.yaml
@@ -18,13 +18,13 @@ spec:
             - |
               echo "Patching volumesnapshotclasses deletion Policy";
               oc patch volumesnapshotclass ocs-storagecluster-rbdplugin-snapclass --type=merge -p '{"deletionPolicy": "Retain"}';
-              oc get volumesnapshotclass ocs-storagecluster-rbdplugin-snapclass;
-              #if [ $? -eq 0 ]
-              #then
-              #    echo "volumesnapshotclass ocs-storagecluster-rbdplugin-snapclass deletionPolicy = Retain applied ok"
-              #else
-              #    echo "Failed to change volumesnapshotclass ocs-storagecluster-rbdplugin-snapclass deletionPolicy"
-              #fi
+              #oc get volumesnapshotclass ocs-storagecluster-rbdplugin-snapclass;
+              if [ $? -eq 0 ]
+              then
+                  echo "volumesnapshotclass ocs-storagecluster-rbdplugin-snapclass deletionPolicy = Retain applied ok"
+              else
+                  echo "Failed to change volumesnapshotclass ocs-storagecluster-rbdplugin-snapclass deletionPolicy"
+              fi
               oc patch volumesnapshotclass ocs-storagecluster-cephfsplugin-snapclass --type=merge -p '{"deletionPolicy": "Retain"}';
               if [ $? -eq 0 ]
               then
